{% set version = "0.2.0" %}

package:
  name: ipython_genutils
  version: {{ version }}

source:
  fn: ipython_genutils-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/i/ipython_genutils/ipython_genutils-{{ version }}.tar.gz
  sha256: eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipython_genutils
    - ipython_genutils.testing
    - ipython_genutils.tests

about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Vestigial utilities from IPython

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - scopatz
    - Carreau
    - takluyver
